//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDTUtoriall
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {

        public int StudentId { get; set; }
        [Required]
        [StringLength(20)]
        public string StudentName { get; set; }
        [Required]
        public int StudentFees { get; set; }
        [StringLength(20)]
        public string StudentCity { get; set; }
    }
}
